/*jshint quotmark: false */
angular.module("liveopsConfigPanel")
.value("realtimeDashboards", [

{
    "id":"overview",
    "dashId":"overview",
    "name":"Overview Dashboard",
    "refreshRate":15000,
    "gridster":{
        "columns":60,
        "minRows":10,
        "maxRows":40,
        "margins":[
            20,
            20
        ],
        "outerMargin":false,
        "draggable":{
            "enabled":true
        },
        "resizable":{
            "enabled":false
        }
    },
    "widgets":[
        {
            "id":"source-switcher-1",
            "type":"sourceSwitcher",
            "config":{
                "groupName":"queue1",
                "sourceType":"queue",
                "items":[

                ],
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Queue:"
                    },
                    "size":{
                        "width":11,
                        "height":3
                    },
                    "position":{
                        "row":0,
                        "col":2
                    }
                }
            }
        },
        {
            "id":"queue-group-1-queue-length",
            "type":"statistic",
            "config":{
                "statistic":"queue-length",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue1",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Current Queue Length"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                      "row":3,
                      "col":2
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-1-queue-duration",
            "type":"statistic",
            "config":{
                "statistic":"queue-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "groupName":"queue1",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Queue Wait Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":8
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-1-queue-abandons",
            "type":"statistic",
            "config":{
                "statistic":"abandon-queue-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue1",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total Abandons"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":2
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
           "id":"queue-group-1-queue-duration-max",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"max",
               "additionalParams":[],
               "displayType": "duration",
               "groupName":"queue1",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Max Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":9,
                       "col":8
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        },
        {
            "id":"source-switcher-2",
            "type":"sourceSwitcher",
            "config":{
                "groupName":"queue2",
                "sourceType":"queue",
                "items":[

                ],
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Queue:"
                    },
                    "size":{
                        "width":11,
                        "height":3
                    },
                    "position":{
                        "row":0,
                        "col":15
                    }
                }
            }
        },
        {
            "id":"queue-group-2-queue-length",
            "type":"statistic",
            "config":{
                "statistic":"queue-length",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue2",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Current Queue Length"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":15
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-2-queue-duration",
            "type":"statistic",
            "config":{
                "statistic":"queue-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "groupName":"queue2",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Queue Wait Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":21
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-2-queue-abandons",
            "type":"statistic",
            "config":{
                "statistic":"abandon-queue-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue2",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total Abandons"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":15
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
           "id":"queue-group-2-queue-duration-max",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"max",
               "additionalParams":[],
               "displayType": "duration",
               "groupName":"queue2",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Max Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":9,
                       "col":21
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        },
        {
            "id":"all-agents-group-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":3
                    },
                    "position":{
                        "row":0,
                        "col":27
                    }
                }
            },
            "chart":{
                "data":"All Agents"
            }
        },
        {
            "id":"all-agents-group-resources-currently-ready",
            "type":"statistic",
            "config":{
                "statistic":"resources-ready",
                "statisticLookup":"value",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Agents Currently Ready"
                    },
                    "unit":"agents",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":27
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-agents-group-resources-currently-away",
            "type":"statistic",
            "config":{
                "statistic":"resources-away",
                "statisticLookup":"value",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Agents Currently Away"
                    },
                    "unit":"agents",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":32
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-agents-group-resources-currently-busy",
            "type":"statistic",
            "config":{
                "statistic":"resources-busy",
                "statisticLookup":"value",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Agents Currently Busy"
                    },
                    "unit":"agents",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":37
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-agents-group-average-conversation-duration",
            "type":"statistic",
            "config":{
                "statistic":"conversation-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Conversation Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":27
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-agents-group-time-to-answer",
            "type":"statistic",
            "config":{
                "statistic":"time-to-answer-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Time To Answer"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":32
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-agents-group-agents-hold-count",
            "type":"statistic",
            "config":{
                "statistic":"resource-hold-duration",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total Holds Triggered"
                    },
                    "unit":"holds",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":37
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-interactions-group-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":3
                    },
                    "position":{
                        "row":0,
                        "col":43
                    }
                }
            },
            "chart":{
                "data":"All Interactions"
            }
        },
        {
            "id":"all-interactions-group-total-interactions-in-queues",
            "type":"statistic",
            "config":{
                "statistic":"queue-length",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total in Queue"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":43
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-interactions-group-max-queue-duration",
            "type":"statistic",
            "config":{
                "statistic":"queue-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Queue Wait Time"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":48
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-interactions-group-total-queue-abandons-for-tenant",
            "type":"statistic",
            "config":{
                "statistic":"abandon-queue-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Queue Abandons"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":53
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-interactions-group-avg-interaction-duration",
            "type":"statistic",
            "config":{
                "statistic":"interaction-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Interaction Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":43
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-interactions-group-total-interactions-in-conversation",
            "type":"statistic",
            "config":{
                "statistic":"interactions-in-conversation-count",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Interactions in Conversation"
                    },
                    "unit":"interactions",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":48
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"all-interactions-group-avg-abandon-time-duration",
            "type":"statistic",
            "config":{
                "statistic":"abandon-time-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Abandon Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":53
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        }]
},
{
    "id":"resource",
    "dashId":"resource",
    "name":"Resource Dashboard",
    "refreshRate":15000,
    "gridster":{
        "columns":60,
        "minRows":10,
        "maxRows":100,
        "margins":[
            20,
            20
        ],
        "outerMargin":false,
        "draggable":{
            "enabled":true
        },
        "resizable":{
            "enabled":false
        }
    },
    "widgets":[
        {
            "id":"ready-resources-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":2
                    },
                    "position":{
                        "row":0,
                        "col":6
                    }
                }
            },
            "chart":{
                "data":"Ready Resources"
            }
        },
        {
            "id":"ready-resources-current",
            "type":"statistic",
            "config":{
                "statistic":"resources-ready",
                "statisticLookup":"value",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Current"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":6
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"ready-resources-max",
            "type":"statistic",
            "config":{
                "statistic":"resources-ready",
                "statisticLookup":"max",
                "additionalParams":['gaugeStart','gaugeEnd'],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":11
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"ready-resources-min",
            "type":"statistic",
            "config":{
                "statistic":"resources-ready",
                "statisticLookup":"min",
                "additionalParams":['gaugeStart','gaugeEnd'],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":16
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"resources-not-ready-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":2
                    },
                    "position":{
                        "row":0,
                        "col":23
                    }
                }
            },
            "chart":{
                "data":"Not Ready Resources"
            }
        },
        {
            "id":"resources-not-ready-current",
            "type":"statistic",
            "config":{
                "statistic":"resources-away",
                "statisticLookup":"value",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":23
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"resources-not-ready-max",
            "type":"statistic",
            "config":{
                "statistic":"resources-away",
                "statisticLookup":"max",
                "additionalParams":['gaugeStart','gaugeEnd'],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":28
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"resources-not-ready-min",
            "type":"statistic",
            "config":{
                "statistic":"resources-away",
                "statisticLookup":"min",
                "additionalParams":['gaugeStart','gaugeEnd'],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":33
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"resources-busy-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":2
                    },
                    "position":{
                        "row":0,
                        "col":40
                    }
                }
            },
            "chart":{
                "data":"Busy Resources"
            }
        },
        {
            "id":"resources-busy-current",
            "type":"statistic",
            "config":{
                "statistic":"resources-busy",
                "statisticLookup":"value",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":40
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"resources-busy-max",
            "type":"statistic",
            "config":{
                "statistic":"resources-busy",
                "statisticLookup":"max",
                "additionalParams":['gaugeStart','gaugeEnd'],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":45
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"resources-busy-min",
            "type":"statistic",
            "config":{
                "statistic":"resources-busy",
                "statisticLookup":"min",
                "additionalParams":['gaugeStart','gaugeEnd'],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min Concurrent"
                    },
                    "unit":"Resources",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":50
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"holds-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":2
                    },
                    "position":{
                        "row":9,
                        "col":6
                    }
                }
            },
            "chart":{
                "data":"Hold Duration"
            }
        },
        {
            "id":"avg-hold-time",
            "type":"statistic",
            "config":{
                "statistic":"resource-hold-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Hold Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":12,
                        "col":6
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"min-hold-time",
            "type":"statistic",
            "config":{
                "statistic":"resource-hold-duration",
                "statisticLookup":"min",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min. Hold Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":12,
                        "col":11
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"max-hold-time",
            "type":"statistic",
            "config":{
                "statistic":"resource-hold-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max. Hold Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":12,
                        "col":16
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"conversation-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":2
                    },
                    "position":{
                        "row":17,
                        "col":6
                    }
                }
            },
            "chart":{
                "data":"In Conversation Duration"
            }
        },
        {
            "id":"avg-convo-duration",
            "type":"statistic",
            "config":{
                "statistic":"conversation-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Conversation Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":19,
                        "col":6
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"min-convo-duration",
            "type":"statistic",
            "config":{
                "statistic":"conversation-duration",
                "statisticLookup":"min",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min. Conversation Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":19,
                        "col":11
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"max-convo-duration",
            "type":"statistic",
            "config":{
                "statistic":"conversation-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max. Conversation Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":19,
                        "col":16
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"tta-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":15,
                        "height":2
                    },
                    "position":{
                        "row":88,
                        "col":6
                    }
                }
            },
            "chart":{
                "data":"Time To Answe Duration"
            }
        },
        {
            "id":"avg-tta",
            "type":"statistic",
            "config":{
                "statistic":"time-to-answer-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Time To Answer"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":90,
                        "col":6
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"min-tta",
            "type":"statistic",
            "config":{
                "statistic":"time-to-answer-duration",
                "statisticLookup":"min",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min. Time To Answer"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":90,
                        "col":11
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"max-tta",
            "type":"statistic",
            "config":{
                "statistic":"time-to-answer-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max. Time To Answer"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":90,
                        "col":16
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        }
    ]
},
{
    "id":"queues",
    "dashId":"queues",
    "name":"Queue Dashboard",
    "refreshRate":15000,
    "gridster":{
        "columns":60,
        "minRows":10,
        "maxRows":40,
        "margins":[
            20,
            20
        ],
        "outerMargin":false,
        "draggable":{
            "enabled":true
        },
        "resizable":{
            "enabled":false
        }
    },
    "widgets":[
        {
            "id":"all-queues-title",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":47,
                        "height":2
                    },
                    "position":{
                        "row":0,
                        "col":5
                    }
                }
            },
            "chart":{
                "data":"All Queues"
            }
        },
        {
            "id":"all-queues-length",
            "type":"statistic",
            "config":{
                "statistic":"queue-length",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Queue Length"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":5
                    }
                }
            }
        },
        {
            "id":"all-queues-calls-percent",
            "type":"statistic",
            "config":{
                "statistic":"calls-answered-percent",
                "statisticLookup":"calls-answered",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Answered < 20s"
                    },
                    "unit":"Answered < 20s",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":10
                    }
                }
            }
        },
        {
            "id":"all-queues-abandons",
            "type":"statistic",
            "config":{
                "statistic":"abandon-queue-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Abandons"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":15
                    }
                }
            }
        },
        {
            "id":"all-queues-avg-wait",
            "type":"statistic",
            "config":{
                "statistic":"queue-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Wait Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":20
                    }
                }
            }
        },
        {
            "id":"all-queues-duration-min",
            "type":"statistic",
            "config":{
                "statistic":"queue-duration",
                "statisticLookup":"min",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min Wait Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":25
                    }
                }
            }
        },
        {
            "id":"all-queues-duration-max",
            "type":"statistic",
            "config":{
                "statistic":"queue-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "duration",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Wait Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":30
                    }
                }
            }
        },
        {
            "id":"all-queues-spacer",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":31,
                        "height":2
                    },
                    "position":{
                        "row":9,
                        "col":5
                    }
                }
            },
            "chart":{
                "data":""
            }
        },
        {
            "id":"source-switcher-1",
            "type":"sourceSwitcher",
            "config":{
                "groupName":"queue1",
                "sourceType":"queue",
                "items":[

                ],
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Queue:"
                    },
                    "size":{
                        "width":15,
                        "height":3
                    },
                    "position":{
                        "row":11,
                        "col":5
                    }
                }
            }
        },
        {
            "id":"queue-group-1-queue-length",
            "type":"statistic",
            "config":{
                "statistic":"queue-length",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue1",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Current Queue Length"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                      "row":14,
                      "col":5
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-1-calls-answered",
            "type":"statistic",
            "config":{
                "statistic":"calls-answered-percent",
                "statisticLookup":"calls-answered",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue1",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Answered < 20s"
                    },
                    "unit":"Answered < 20s",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":14,
                        "col":10
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-1-queue-abandons",
            "type":"statistic",
            "config":{
                "statistic":"abandon-queue-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue1",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total Abandons"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":14,
                        "col":15
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
           "id":"queue-group-1-queue-duration-avg",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"avg",
               "additionalParams":[],
               "displayType": "duration",
               "groupName":"queue1",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Avg Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":19,
                       "col":5
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        },
        {
           "id":"queue-group-1-queue-duration-min",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"min",
               "additionalParams":[],
               "displayType": "duration",
               "groupName":"queue1",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Min Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":19,
                       "col":10
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        },
        {
           "id":"queue-group-1-queue-duration-max",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"max",
               "displayType": "duration",
               "additionalParams":[],
               "groupName":"queue1",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Max Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":19,
                       "col":15
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        },
        {
            "id":"source-switcher-2",
            "type":"sourceSwitcher",
            "config":{
                "groupName":"queue2",
                "sourceType":"queue",
                "items":[

                ],
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Queue:"
                    },
                    "size":{
                        "width":15,
                        "height":3
                    },
                    "position":{
                        "row":11,
                        "col":21
                    }
                }
            }
        },
        {
            "id":"queue-group-2-queue-length",
            "type":"statistic",
            "config":{
                "statistic":"queue-length",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue2",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Current Queue Length"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                      "row":14,
                      "col":21
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-2-calls-answered",
            "type":"statistic",
            "config":{
                "statistic":"calls-answered-percent",
                "statisticLookup":"calls-answered",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue2",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Answered < 20s"
                    },
                    "unit":"Answered < 20s",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":14,
                        "col":26
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
            "id":"queue-group-2-queue-abandons",
            "type":"statistic",
            "config":{
                "statistic":"abandon-queue-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "groupName":"queue2",
                "resourceIdName":"queue-id",
                "resourceId":null,
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total Abandons"
                    },
                    "unit":"customers",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":14,
                        "col":31
                    }
                }
            },
            "chart":{
                "indicator":{

                }
            }
        },
        {
           "id":"queue-group-2-queue-duration-avg",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"avg",
               "additionalParams":[],
               "displayType": "time",
               "groupName":"queue2",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Avg Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":19,
                       "col":21
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        },
        {
           "id":"queue-group-2-queue-duration-min",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"min",
               "additionalParams":[],
               "displayType": "time",
               "groupName":"queue2",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Min Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":19,
                       "col":26
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        },
        {
           "id":"queue-group-2-queue-duration-max",
           "type":"statistic",
           "config":{
               "statistic":"queue-duration",
               "statisticLookup":"max",
               "additionalParams":[],
               "displayType": "time",
               "groupName":"queue2",
               "resourceIdName":"queue-id",
               "resourceId":null,
               "ui":{
                   "title":{
                       "show":true,
                       "text":"Max Queue Wait Time"
                   },
                   "unit":"",
                   "size":{
                       "width":5,
                       "height":5
                   },
                   "position":{
                       "row":19,
                       "col":31
                   }
               }
           },
           "chart":{
               "indicator":{

               }
           }
        }
    ]
},
{
    "id":"interactions",
    "dashId":"interactions",
    "name":"Interactions Dashboard",
    "refreshRate":15000,
    "gridster":{
        "columns":60,
        "minRows":10,
        "maxRows":40,
        "margins":[
            20,
            20
        ],
        "outerMargin":false,
        "draggable":{
            "enabled":true
        },
        "resizable":{
            "enabled":false
        }
    },
    "widgets":[
        {
            "id":"00000000-0000-0000-000000000001",
            "type":"title",
            "config":{
                "ui":{
                    "size":{
                        "width":40,
                        "height":2
                    },
                    "position":{
                        "row":0,
                        "col":10
                    }
                }
            },
            "chart":{
                "data":"All Interactions"
            }
        },
        {
            "id":"int-in-convo-live",
            "type":"statistic",
            "config":{
                "statistic":"interactions-in-conversation-count",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"In Conversation"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":10
                    }
                }
            }
        },
        {
            "id":"int-start-instance",
            "type":"statistic",
            "config":{
                "statistic":"interaction-start-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Interactions Started"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":15
                    }
                }
            }
        },
        {
            "id":"int-in-queue",
            "type":"statistic",
            "config":{
                "statistic":"queue-length",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Interactions In Queue"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":20
                    }
                }
            }
        },
        {
            "id":"int-aband-queue-inst",
            "type":"statistic",
            "config":{
                "statistic":"abandon-queue-instance",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Queues Abandoned"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":25
                    }
                }
            }
        },
        {
            "id":"int-ivr-abandon",
            "type":"statistic",
            "config":{
                "statistic":"interactions-in-routing-abandon-count",
                "statisticLookup":"recordsCount",
                "additionalParams":[],
                "displayType": "count",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"IVR Abandons"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":30
                    }
                }
            }
        },
        {
            "id":"avg-aband-time",
            "type":"statistic",
            "config":{
                "statistic":"abandon-time-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Abandon Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":35
                    }
                }
            }
        },
        {
            "id":"max-aband-time",
            "type":"statistic",
            "config":{
                "statistic":"abandon-time-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Abandon Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":40
                    }
                }
            }
        },
        {
            "id":"min-aband-time",
            "type":"statistic",
            "config":{
                "statistic":"abandon-time-duration",
                "statisticLookup":"min",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min Abandon Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":3,
                        "col":45
                    }
                }
            }
        },
        {
            "id":"avg-interaction-dur",
            "type":"statistic",
            "config":{
                "statistic":"interaction-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Interaction Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":10
                    }
                }
            }
        },
        {
            "id":"total-interaction-dur",
            "type":"statistic",
            "config":{
                "statistic":"interaction-duration",
                "statisticLookup":"total",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total Interaction Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":15
                    }
                }
            }
        },
        {
            "id":"max-interaction-dur",
            "type":"statistic",
            "config":{
                "statistic":"interaction-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Interaction Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":20
                    }
                }
            }
        },
        {
            "id":"min-interaction-dur",
            "type":"statistic",
            "config":{
                "statistic":"interaction-duration",
                "statisticLookup":"min",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min Interaction Time"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":25
                    }
                }
            }
        },
        {
            "id":"avg-hold-duration",
            "type":"statistic",
            "config":{
                "statistic":"interaction-hold-duration",
                "statisticLookup":"avg",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Avg. Hold Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":30
                    }
                }
            }
        },
        {
            "id":"total-hold-duration",
            "type":"statistic",
            "config":{
                "statistic":"interaction-hold-duration",
                "statisticLookup":"total",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Total Hold Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":35
                    }
                }
            }
        },
        {
            "id":"max-hold-duration",
            "type":"statistic",
            "config":{
                "statistic":"interaction-hold-duration",
                "statisticLookup":"max",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Max Hold Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":40
                    }
                }
            }
        },
        {
            "id":"min-hold-duration",
            "type":"statistic",
            "config":{
                "statistic":"interaction-hold-duration",
                "statisticLookup":"min",
                "additionalParams":[],
                "displayType": "time",
                "ui":{
                    "title":{
                        "show":true,
                        "text":"Min Hold Duration"
                    },
                    "unit":"",
                    "size":{
                        "width":5,
                        "height":5
                    },
                    "position":{
                        "row":9,
                        "col":45
                    }
                }
            }
        }
    ]
}

]);
