angular.module('liveopsConfigPanel').constant('mockDashboard', {
            "id":"default",
            "dashId":"default1",
            "name":"Default Dashboard",
            "gridster":{
                "mobileModeEnabled":false,
                "columns":24,
                "minRows":10,
                "maxRows":30,
                "margins":[
                    40,
                    40
                ],
                "outerMargin":false,
                "draggable":{
                    "enabled":true
                },
                "resizable":{
                    "enabled":true
                }
            },
            "config":{
                "ui":{
                    "size":{
                        "autoResize":true
                    }
                }
            },
            "widgets":[
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"abandonTimeMin",
                        "refreshRate":10000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"abandonTimeMax",
                        "refreshRate":10000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"abandonTimeAvg",
                        "refreshRate":10000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"handleTimeMin",
                        "refreshRate":10000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"handleTimeMax",
                        "refreshRate":17500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"handleTimeAvg",
                        "refreshRate":17500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"interactionTimeMin",
                        "refreshRate":17500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"interactionTimeMax",
                        "refreshRate":17500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"interactionTimeAvg",
                        "refreshRate":30000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"agentTalkTimeMin",
                        "refreshRate":30000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"agentTalkTimeMax",
                        "refreshRate":30000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"agentTalkTimeAvg",
                        "refreshRate":30000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"timeToAnswerMin",
                        "refreshRate":7500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"timeToAnswerMax",
                        "refreshRate":7500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"timeToAnswerAvg",
                        "refreshRate":7500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"wrapUpTimeMin",
                        "refreshRate":7500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"wrapUpTimeMax",
                        "refreshRate":7500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"wrapUpTimeAvg",
                        "refreshRate":12000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"holdTimeMin",
                        "refreshRate":12000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"holdTimeMax",
                        "refreshRate":12000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"holdTimeAvg",
                        "refreshRate":12000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"queueDurationMin",
                        "refreshRate":12000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"queueDurationMax",
                        "refreshRate":12000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                },
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"queueDurationAvg",
                        "refreshRate":17500,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "indicator":{}
                    }
                }
            ]
        });