angular.module('liveopsConfigPanel').constant('mockDashboard', {
            "id":"default",
            "dashId":"default1",
            "name":"Default Dashboard",
            "gridster":{
                "mobileModeEnabled":false,
                "columns":24,
                "minRows":10,
                "maxRows":30,
                "margins":[
                    0,
                    40
                ],
                "outerMargin":false,
                "draggable":{
                    "enabled":true
                },
                "resizable":{
                    "enabled":true
                }
            },
            "config":{
                "ui":{
                    "size":{
                        "autoResize":true
                    }
                }
            },
            "widgets":[
                {
                    "id":"00000000-0000-0000-000000000003",
                    "type":"statistic",
                    "config":{
                        "statistic":"abandonTimeMin",
                        "refreshRate":5000,
                        "ui":{
                            "title":{
                                "show":true,
                                "text":"Abandon Time (min)"
                            },
                            "size":{
                                "width":3,
                                "height":4
                            }
                        }
                    },
                    "chart":{
                        "data":0.1,
                        "indicator":{}
                    }
                }
            ]
        });